apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: skim-test
  name: skim-test
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: skim-test
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: skim-test
    spec:
      containers:
      - image: cmscloud/standalone:cmssw_10_6_25-slc7_amd64_gcc700
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
        imagePullPolicy: Always
        name: skim-test
        resources:
          limits:
            cpu: 4
            memory: 4Gi
          requests:
            cpu: 2
            memory: 2Gi
        volumeMounts:
        - mountPath: /home/cmsusr
          name: cache-vol
        - mountPath: /home/cmsusr/run.sh
          name: skim-test-exe-configmap
          subPath: run.sh
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      nodeSelector:
        kubernetes.io/hostname: river-c030.ssl-hep.org
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
      - name: cache-vol
        emptyDir: {}
      - name: skim-test-exe-configmap
        configMap: 
          name: skim-test-exe-configmap
          items:
          - key: run.sh
            path: run.sh
          defaultMode: 0777
