resources:
  - deploy.yaml

configMapGenerator:
  - name: xrootd-redi-conf
    files:
      - xrootd-third-party-copy.cfg
      - auth-file-noauth
  - name: xrootd-redi-supervisor
    files:
      - supervisord.conf

secretGenerator:
- name: telegraf-conf
  files:
    - telegraf.conf
- name: https-self-certs
  files:
    - OSG-Test-CA.pem

generatorOptions:
  disableNameSuffixHash: true

commonLabels:
  app: xrootd-redi-a
