resources:
  - deploy.yaml

configMapGenerator:
  - name: xrootd-server-conf
    files:
      - xrootd-third-party-copy.cfg
      - auth-file-noauth
      - makeFile
  - name: xrootd-server-supervisor
    files:
      - supervisord.conf

generatorOptions:
  disableNameSuffixHash: true

commonLabels:
  app: xrootd-server-a
