apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: us-cms-datalake-origin-redi
  name: us-cms-datalake-origin-redi
spec:
  selector:
    matchLabels:
      k8s-app: us-cms-datalake-origin-redi
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: us-cms-datalake-origin-redi
    spec:
      # tolerations:
      # - key: "nautilus.io/stashcache"
      #   operator: "Exists"
      #   effect: "NoSchedule"
      # - key: "nautilus.io/noceph" 
      #   operator: "Exists"
      #   effect: "NoSchedule"
      # - key: "nautilus.io/ceph" 
      #   operator: "Exists"
      #   effect: "NoSchedule"
      # - key: "nautilus.io/testing" 
      #   operator: "Exists"
      #   effect: "NoSchedule"
      hostNetwork: true
      containers:
      - env:
        - name: OSG_FQDN
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        image: jguiang/us-cms-datalake-cluster:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 2094
        - containerPort: 2213
        name: us-cms-datalake-origin-redi
        resources:
          limits:
            cpu: 20
            memory: 20Gi
          requests:
            cpu: 2
            memory: 2Gi
        volumeMounts:
        - mountPath: /mnt
          name: ephemeral
        - mountPath: /etc/xrootd/xrootd.cfg
          name: xrootd-redi-conf
          subPath: xrootd.cfg
        - mountPath: /etc/xrootd/auth-file-noauth
          name: xrootd-redi-conf
          subPath: auth-file-noauth
        - mountPath: /etc/supervisord.d/10-xrootd.conf
          name: xrootd-redi-supervisor
          subPath: supervisord.conf
        - mountPath: /etc/pki/CA/private/OSG-Test-CA.key
          name: ca
          subPath: OSG-Test-CA.pem
      # nodeSelector:
      #   kubernetes.io/hostname: k8s-igrok-02.calit2.ucsd.edu
      dnsPolicy: ClusterFirstWithHostNet
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
      - name: ephemeral
        emptyDir: {}
      - name: ca
        secret:
          secretName: https-self-certs
          items:
          - key: OSG-Test-CA.pem
            path: OSG-Test-CA.pem
          defaultMode: 0644
      - name: xrootd-redi-conf
        configMap: 
          name: xrootd-redi-conf
          items:
          - key: xrootd.cfg
            path: xrootd.cfg
          - key: auth-file-noauth
            path: auth-file-noauth
      - name: xrootd-redi-supervisor
        configMap: 
          name: xrootd-redi-supervisor
          items:
          - key: supervisord.conf
            path: supervisord.conf
