apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: us-cms-datalake-origin-redi
  name: us-cms-datalake-origin-redi
spec:
  selector:
    matchLabels:
      k8s-app: us-cms-datalake-origin-redi
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: us-cms-datalake-origin-redi
    spec:
      hostNetwork: True
      containers:
      - image: jguiang/us-cms-datalake-cluster:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 1094
        - containerPort: 9001
        name: us-cms-datalake-origin-redi
        resources:
          limits:
            cpu: 48
            memory: 100Gi
          requests:
            cpu: 2
            memory: 4Gi
        volumeMounts:
        - mountPath: /mnt
          name: ephemeral
        - mountPath: /etc/xrootd/xrootd.cfg
          name: xrootd-redi-conf
          subPath: xrootd.cfg
        - mountPath: /etc/xrootd/scitokens.cfg
          name: xrootd-redi-conf
          subPath: scitokens.cfg
        - mountPath: /etc/xrootd/auth-file
          name: xrootd-redi-conf
          subPath: auth-file
        - mountPath: /etc/supervisord.d/10-xrootd.conf
          name: xrootd-redi-supervisor
          subPath: supervisord.conf
        - mountPath: /etc/grid-security/hostcert.pem
          name: hostcert
        - mountPath: /etc/grid-security/hostkey.pem
          name: hostkey
      nodeSelector:
        kubernetes.io/hostname: k8s1-pb10.ultralight.org
      dnsPolicy: Default
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
      - name: ephemeral
        emptyDir: {}
      - name: xrootd-redi-conf
        configMap: 
          name: xrootd-redi-conf
          items:
          - key: xrootd.cfg
            path: xrootd.cfg
          - key: scitokens.cfg
            path: scitokens.cfg
          - key: auth-file
            path: auth-file
      - name: xrootd-redi-supervisor
        configMap: 
          name: xrootd-redi-supervisor
          items:
          - key: supervisord.conf
            path: supervisord.conf
      - name: hostcert
        hostPath:
          path: /etc/grid-security/hostcert.pem
          type: File
      - name: hostkey
        hostPath:
          path: /etc/grid-security/hostkey.pem
          type: File
