apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: us-cms-datalake-origin-redi
  name: us-cms-datalake-origin-redi
spec:
  selector:
    matchLabels:
      k8s-app: us-cms-datalake-origin-redi
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: us-cms-datalake-origin-redi
    spec:
      hostNetwork: true
      containers:
      - image: jguiang/us-cms-datalake-cluster:latest
        imagePullPolicy: Always
        env:
        - name: OSG_FQDN
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName 
        ports:
        - containerPort: 2094
        - containerPort: 2213
        name: us-cms-datalake-origin-redi
        resources:
          limits:
            cpu: 20
            memory: 20Gi
          requests:
            cpu: 2
            memory: 2Gi
        volumeMounts:
        - mountPath: /mnt
          name: ephemeral
        - mountPath: /etc/xrootd/xrootd.cfg
          name: xrootd-redi-conf
          subPath: xrootd.cfg
        - mountPath: /etc/scitokens/scitokens.cfg
          name: xrootd-redi-conf
          subPath: scitokens.cfg
        - mountPath: /etc/xrootd/auth-file-noauth
          name: xrootd-redi-conf
          subPath: auth-file-noauth
        - mountPath: /etc/supervisord.d/10-xrootd.conf
          name: xrootd-redi-supervisor
          subPath: supervisord.conf
      # nodeSelector:
      #   kubernetes.io/hostname: k8s-igrok-02.calit2.ucsd.edu
      dnsPolicy: Default
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
      - name: ephemeral
        emptyDir: {}
      - name: xrootd-redi-conf
        configMap: 
          name: xrootd-redi-conf
          items:
          - key: xrootd.cfg
            path: xrootd.cfg
          - key: scitokens.cfg
            path: scitokens.cfg
          - key: auth-file-noauth
            path: auth-file-noauth
      - name: xrootd-redi-supervisor
        configMap: 
          name: xrootd-redi-supervisor
          items:
          - key: supervisord.conf
            path: supervisord.conf
