resources:
  - deploy.yaml

configMapGenerator:
  - name: xrootd-redi-conf
    files:
      - xrootd.cfg
      - scitokens.cfg
      - auth-file
      - grid-mapfile
  - name: xrootd-redi-supervisor
    files:
      - supervisord.conf

generatorOptions:
  disableNameSuffixHash: true

commonLabels:
    app: us-cms-datalake-origin-redi
