apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: us-cms-datalake-origin
  name: us-cms-datalake-origin
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: us-cms-datalake-origin
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: us-cms-datalake-origin
    spec:
      hostNetwork: True
      containers:
      - image: jguiang/us-cms-datalake-cluster:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 2811
        name: us-cms-datalake-origin
        resources:
          limits:
            cpu: 48
            memory: 100Gi
            ephemeral-storage: 50Gi
          requests:
            cpu: 4
            memory: 8Gi
            ephemeral-storage: 20Gi
        volumeMounts:
        - mountPath: /mnt
          name: datalake-origin-pervol
        - mountPath: /etc/xrootd/xrootd.cfg
          name: origin-conf
          subPath: xrootd.cfg
        - mountPath: /etc/xrootd/scitokens.cfg
          name: origin-conf
          subPath: scitokens.cfg
        - mountPath: /etc/xrootd/auth-file
          name: origin-conf
          subPath: auth-file
        - mountPath: /etc/supervisord.d/10-xrootd.conf
          name: origin-supervisor
          subPath: supervisord.conf
        - mountPath: /etc/grid-security/hostcert.pem
          name: hostcert
        - mountPath: /etc/grid-security/hostkey.pem
          name: hostkey
      nodeSelector:
        kubernetes.io/hostname: k8s1-pb10.ultralight.org
      dnsPolicy: Default
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
      - name: datalake-origin-pervol
        persistentVolumeClaim:
          claimName: pvc-xrootd-data-lake-origin-caltech-k8s1-pb10-ultralight-org-persistent-7
      - name: origin-conf
        configMap: 
          name: origin-conf
          items:
          - key: xrootd.cfg
            path: xrootd.cfg
          - key: scitokens.cfg
            path: scitokens.cfg
          - key: auth-file
            path: auth-file
      - name: origin-supervisor
        configMap: 
          name: origin-supervisor
          items:
          - key: supervisord.conf
            path: supervisord.conf
      - name: hostcert
        hostPath:
          path: /etc/grid-security/hostcert.pem
          type: File
      - name: hostkey
        hostPath:
          path: /etc/grid-security/hostkey.pem
          type: File
