resources:
  - deploy.yaml

configMapGenerator:
  - name: origin-conf
    files:
      - xrootd.cfg
      - auth-file-noauth
      - makeFile
  - name: origin-supervisor
    files:
      - supervisord.conf

generatorOptions:
  disableNameSuffixHash: true

commonLabels:
  app: us-cms-datalake-origin
