resources:
  - deploy.yaml

configMapGenerator:
  - name: origin-conf
    files:
      - xrootd.cfg
      - scitokens.cfg
      - auth-file
      - grid-mapfile
  - name: origin-supervisor
    files:
      - supervisord.conf

generatorOptions:
  disableNameSuffixHash: true

commonLabels:
  app: us-cms-datalake-origin
